### ISSUE TITLE
Use deny mode

### ISSUE THREAD

**Issue by friedger** [dartman10/bnstransfer#1]
There should be post conditions and deny mode:
https://github.com/dartman10/bnstransfer/blob/master/src/components/ContractCallBnsTransfer.js#L37

**Comment by dartman10** [comment]
hi @friedger - thank you for taking the time to check and for the feedback!

I added the needed post-condition previously and I temporarily applied it on a new repo (in case i break something):
  [https://github.com/dartman10/bnstransfer-v2](https://github.com/dartman10/bnstransfer-v2)
However, I ended up pointing the site bnstransfer.com to this new repo.  :)

There's actually one more thing I need to do involving zonefile.  The site should provide users an option either to delete the zonefile or keep it and carry over to the new address.

Cheers!

**Comment by dartman10** [comment]
Direct link to post-condition: 
[https://github.com/dartman10/bnstransfer-v2/blob/e58d829c2de7ceb8a22d1ec8f7b257c609118a6e/src/components/ContractCallBnsTransfer.js#L127](https://github.com/dartman10/bnstransfer-v2/blob/e58d829c2de7ceb8a22d1ec8f7b257c609118a6e/src/components/ContractCallBnsTransfer.js#L127)

**Comment by friedger** [comment]
Good
